### ISSUE TITLE
is it reasonable to use the labels of V_U?

### ISSUE THREAD

**Issue by likuanppd** [MengmeiZ/LafAK#1]
Hi MengmeiZ!

To generate attack, the labels of V_U are used in Eq(12). To the best of my knowledge, these labels can't be used. Many papers utilize the predicted labels of V_U as ground truth to compute the loss.

**Comment by MengmeiZ** [comment]
Thank you for your interest in our work.

In the experiment, We also consider the case that the attacker has no access to true test labels y_U, which is common in practical attack scenarios. As shown in Fig. 8, we can observe that there is no significant decrease for our model LafAK without true labels of test data.
